// <auto-generated />
using System;
using API_TEGRA.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_TEGRA.Migrations
{
    [DbContext(typeof(ContextoTegra))]
    partial class ContextoTegraModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_TEGRA.Modelo.Box", b =>
                {
                    b.Property<int>("Id_Box")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Box_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Product")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId_Product")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Box");

                    b.HasIndex("ProductId_Product");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("API_TEGRA.Modelo.Operation", b =>
                {
                    b.Property<int>("Id_Operation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BoxId_Box")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Box")
                        .HasColumnType("int");

                    b.Property<int>("Id_Operation_Type")
                        .HasColumnType("int");

                    b.Property<int?>("Operation_TypeId_Operation_Type")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Operation");

                    b.HasIndex("BoxId_Box");

                    b.HasIndex("Operation_TypeId_Operation_Type");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("API_TEGRA.Modelo.Operation_Type", b =>
                {
                    b.Property<int>("Id_Operation_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Operation_Type");

                    b.ToTable("Operation_Types");
                });

            modelBuilder.Entity("API_TEGRA.Modelo.Product", b =>
                {
                    b.Property<int>("Id_Product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Product");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("API_TEGRA.Modelo.Box", b =>
                {
                    b.HasOne("API_TEGRA.Modelo.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId_Product");
                });

            modelBuilder.Entity("API_TEGRA.Modelo.Operation", b =>
                {
                    b.HasOne("API_TEGRA.Modelo.Box", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId_Box");

                    b.HasOne("API_TEGRA.Modelo.Operation_Type", "Operation_Type")
                        .WithMany()
                        .HasForeignKey("Operation_TypeId_Operation_Type");
                });
#pragma warning restore 612, 618
        }
    }
}
